# Generated by Django 4.1.1 on 2022-09-23 16:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('info', '0002_author_tag_remove_stories_desc_stories_content_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='stories',
            name='username',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='authors', to='info.author'),
        ),
    ]
