# Generated by Django 4.1.1 on 2022-09-23 17:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('info', '0003_alter_stories_username'),
    ]

    operations = [
        migrations.RenameField(
            model_name='stories',
            old_name='username',
            new_name='author',
        ),
    ]
