# Generated by Django 4.1.1 on 2022-09-23 17:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('info', '0004_rename_username_stories_author'),
    ]

    operations = [
        migrations.RenameField(
            model_name='stories',
            old_name='tag',
            new_name='tags',
        ),
    ]
