# Generated by Django 4.1.1 on 2022-09-24 15:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('info', '0005_rename_tag_stories_tags'),
    ]

    operations = [
        migrations.AddField(
            model_name='author',
            name='bio',
            field=models.CharField(default='anonymus', max_length=200),
            preserve_default=False,
        ),
    ]
