# Generated by Django 4.1.1 on 2022-09-24 15:55

import ckeditor.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('info', '0006_author_bio'),
    ]

    operations = [
        migrations.AlterField(
            model_name='stories',
            name='content',
            field=ckeditor.fields.RichTextField(),
        ),
    ]
