# Generated by Django 4.1.1 on 2022-09-24 15:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('info', '0007_alter_stories_content'),
    ]

    operations = [
        migrations.AlterField(
            model_name='stories',
            name='content',
            field=models.TextField(),
        ),
    ]
